### ISSUE TITLE
auto-quit not working, no more than one minute connected

### ISSUE THREAD

**Issue by HiA-o** [marlester-dev/ReallyFakePlayers#28]
I am trying to configure the fake players to stay connected longer but the maximum time they are connected is one minute.. If i config it like this for example:
```
auto-join:
  enable: true
  # Delay on the startup
  startup-delay: 3
  delay:
    min: 80
    max: 120
# Each fake player will leave the server after a delay that you set below
auto-quit:
  enable: true
  delay:
    min: 600
    max: 800
```

After one minute they are disconnected, no matter how you configure it, even if a config:
`auto-quit:
  enable: false`

they still disconected

Also, `invulnerable: false` now working also
